pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS=credentials('dockerhub')
    }
    stages {
        stage('Trigged') {
            steps {
                echo "Hello $DOCKERHUB_CREDENTIALS_USR from Slave"
            }
        }
        stage('Login Stage') {
          steps {
            echo "Login : Logging in . . ."
            bat 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
          }
        }
        stage('Pull from Docker') {
          steps {
               dir('Lab_jenkins_dockercompose') { // change directory to Lab_docker_Jenkins
                    echo "Pull . ."
                    bat "docker-compose pull"
                }
          }
        }
        stage('Start stage') {
            steps {
                dir('Lab_jenkins_dockercompose') { // change directory to Lab_docker_Jenkins
                    echo "Start . ."
                    bat "docker-compose up -d"
                }
            }
        }
 
}
}
