pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS=credentials('dockerhub')
    }
 
    stages {
        stage('Initialize Stage') {
            steps {
            
                echo 'Initial : Delete  containers and images'
                 dir('Lab_jenkins_dockercompose') { // change directory to Lab_docker_Jenkins
                    echo "Current path is ${pwd()}"
                    bat "docker-compose down --rmi all --volumes || true"
                }
            }
        }


        stage('Build Stage') {
            steps {
                dir('Lab_jenkins_dockercompose') { // change directory to Lab_docker_Jenkins
                    echo "Current path is ${pwd()}"
                    bat "docker-compose build"
                }
            }
        }
        stage('Login Stage') {
            steps {
                echo "Login: Logging in..."
                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD']]) {
                    bat "echo \${DOCKERHUB_PASSWORD} | docker login -u \${DOCKERHUB_USERNAME} --password-stdin dckr_pat_oR-oMV0G651OzkdvdMJALu7U2n0"
                }
            }
        }



        stage('Push Stage') {
            steps {
                dir('Lab_jenkins_dockercompose') { // change directory to Lab_docker_Jenkins
                    echo "Push : Current path is ${pwd()}"
                    bat "docker-compose push"
                }
            }
        }
        stage('Trigger Slave Dockerhub last up') {
            steps {
                dir('Lab_jenkins_dockercompose') { // change directory to Lab_docker_Jenkins
                    echo "Trigger : calling Slave job . . ."
                    bat 'echo "HELLO ${DOCKERHUB_CREDENTIALS_USR}"'
                    build job: 'Slave', parameters: [string(name: 'DOCKERHUB_CREDENTIALS_USR', value: env.DOCKERHUB_CREDENTIALS_USR), string(name: 'DOCKERHUB_CREDENTIALS_PSW', value: env.DOCKERHUB_CREDENTIALS_PSW)]
                }
            }
        }

    
       

    }
}
